const {chromium}=require('playwright');const assert=require('node:assert/strict');
const url=new URL('/trung-thu/?inspect',process.env.LOVE_TEST_URL||'http://127.0.0.1:5002/').href;
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{
 const p=await b.newPage({viewport:{width:1440,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);await p.waitForFunction(()=>window.__midAutumn?.state().assetsReady);await p.evaluate(()=>window.__midAutumn.seek('outro',10));const initial=await p.evaluate(()=>window.__midAutumn.measure().contact);await p.setViewportSize({width:1280,height:720});await p.waitForTimeout(80);const resized=await p.evaluate(()=>window.__midAutumn.measure().contact);assert.ok(Math.hypot(initial.x-resized.x,initial.y-resized.y)<2,'Resize should preserve current letter position during approach');assert.equal(await p.evaluate(()=>window.__midAutumn.state().elapsed),10);await p.locator('#pause').click();await p.waitForTimeout(750);assert.ok(await p.evaluate(()=>window.__midAutumn.state().elapsed>10.6));
 // Simulate the browser's visibility event at the page seam; physical tab switching is checked separately.
 await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});const hiddenAt=await p.evaluate(()=>window.__midAutumn.state().elapsed);await p.waitForTimeout(180);assert.equal(await p.evaluate(()=>window.__midAutumn.state().elapsed),hiddenAt);assert.equal(await p.evaluate(()=>window.__midAutumn.state().frame),0);await p.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});await p.waitForTimeout(120);assert.ok(await p.evaluate(()=>window.__midAutumn.state().elapsed)>hiddenAt);
 await p.emulateMedia({reducedMotion:'reduce'});await p.waitForFunction(()=>window.__midAutumn.state().reduced);assert.equal(await p.evaluate(()=>window.__midAutumn.state().frame),0);assert.equal(await p.locator('#next-scene').isVisible(),true);await p.emulateMedia({reducedMotion:'no-preference'});await p.waitForFunction(()=>!window.__midAutumn.state().reduced);assert.equal(await p.locator('#pause').isVisible(),true);
 // CSS zoom changes the same geometry assumptions as enlarged page content; not a claim of browser UI zoom testing.
 for(const zoom of [.8,1.25,2]){await p.evaluate(zoom=>document.documentElement.style.zoom=zoom,zoom);await p.evaluate(()=>window.__midAutumn.seek('outro',15));assert.ok((await p.evaluate(()=>window.__midAutumn.measure())).error<=8,`Zoom ${zoom}`);}
 await p.evaluate(()=>document.documentElement.style.zoom='');await p.emulateMedia({reducedMotion:'reduce'});await p.setViewportSize({width:320,height:568});await p.evaluate(()=>window.__midAutumn.seek('journey',21));
 for(const id of ['sound','next-scene','skip']){const box=await p.locator('#'+id).boundingBox();assert.ok(box.x>=0&&box.x+box.width<=320&&box.y>=0&&box.y+box.height<=568,`${id} clipped`);assert.ok(box.height>=44);}
 await p.screenshot({path:'output/playwright/v21-320-controls.png'});assert.deepEqual(errors,[]);await p.close();
 // A timed-out load must give control back; retries use fresh URLs and can recover.
 const slow=await b.newPage({reducedMotion:'reduce'});let shouldFail=true;await slow.route('**/hang-*.webp*',async route=>{if(shouldFail)await route.abort();else await route.continue();});await slow.goto(url);await slow.waitForFunction(()=>window.__midAutumn?.state().assetIssue);await slow.locator('#begin').click();await slow.locator('#light-all').click();shouldFail=false;await slow.locator('#retry-assets').click();await slow.waitForFunction(()=>window.__midAutumn.state().mode==='journey');assert.equal(await slow.locator('#loading-actions').isHidden(),true);await slow.close();
 console.log('PASS approach resize continuity, simulated visibility, dynamic reduced motion, CSS zoom, 320px controls and asset retry');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
