const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const base=process.env.LOVE_TEST_URL||'http://127.0.0.1:5002/';
const url=new URL('/trung-thu/?inspect',base).href;
async function ready(page){await page.goto(url);await page.waitForFunction(()=>window.__midAutumn?.state().assetsReady);}
async function start(page){await page.locator('#begin').click();for(let i=0;i<5;i++)await page.locator('.stitch').nth(i).click();await page.waitForFunction(()=>document.body.dataset.mode==='journey');}
async function wish(page,text){await page.locator('#to-wish').click();await page.locator('#wish').fill(text);await page.locator('#send-wish').click();}
async function advance(page,count){for(let i=0;i<count;i++)await page.locator('#next-scene').click();}
(async()=>{fs.mkdirSync('output/playwright',{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[],api=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('/api/'))api.push(r.url());});await ready(page);
 assert.equal(await page.locator('.chapter[data-view=wish]').isDisabled(),true);
 await start(page);await page.locator('#pause').click();const before=await page.evaluate(()=>window.__midAutumn.state().elapsed);await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>window.__midAutumn.state().elapsed),before);
 await page.locator('#pause').click();await page.waitForFunction(()=>document.body.dataset.mode==='feast',{},{timeout:38000});console.log('PASS main film: 5/5, pause/resume, automatic feast');
 await page.locator('.cake-option[data-cake="dẻo"]').click();await page.locator('#to-wish').click();await page.locator('#wish').fill('   ');await page.locator('#send-wish').click();assert.equal(await page.locator('body').getAttribute('data-mode'),'wish');
 const text='Mong mình vẫn có nhau 🌕 <b>mỗi mùa trăng</b>';await page.locator('#wish').fill(text);await page.locator('#send-wish').click();await page.waitForFunction(()=>window.__midAutumn.state().elapsed>=14.1,{},{timeout:18000});assert.ok((await page.evaluate(()=>window.__midAutumn.measure())).error<=8);await page.screenshot({path:'output/playwright/v21-live-receive.png'});await page.waitForFunction(()=>document.body.dataset.mode==='ending',{},{timeout:12000});assert.equal(await page.locator('#ending-wish').textContent(),text);assert.equal(await page.locator('#ending-wish b').count(),0);
 await page.locator('#replay').click();await page.keyboard.press('Escape');assert.equal(await page.locator('body').getAttribute('data-mode'),'ending');assert.equal(await page.locator('#ending-wish').textContent(),text);
 await page.locator('#sound').click();assert.equal(await page.locator('#sound').getAttribute('aria-pressed'),'false');await page.locator('#sound').click();assert.equal(await page.locator('#sound').getAttribute('aria-pressed'),'true');
 await page.locator('#restart').click();assert.deepEqual(await page.evaluate(()=>{const s=window.__midAutumn.state();return[s.mode,s.lit,s.wishText]}),['home',0,'']);assert.deepEqual(errors,[]);assert.deepEqual(api,[]);await page.close();console.log('PASS real outro, receiving, escaped text, replay, reset, audio controls, zero API calls');
 for(const fallback of [false,true]){
 const p=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});const errs=[];p.on('pageerror',e=>errs.push(e.message));if(fallback)await p.route('**/vendor/three-r128.min.js',r=>r.abort());await ready(p);await start(p);assert.equal(await p.evaluate(()=>window.__midAutumn.state().frame),0);await advance(p,6);await wish(p,'🌕'.repeat(241));assert.equal(await p.locator('body').getAttribute('data-mode'),'wish');await p.locator('#wish').fill('🌕'.repeat(240));await p.locator('#send-wish').click();await advance(p,2);assert.equal(await p.locator('body').getAttribute('data-shot'),'receive');assert.ok((await p.evaluate(()=>window.__midAutumn.measure())).error<=8);const first=await p.screenshot();await p.waitForTimeout(200);assert.ok(first.equals(await p.screenshot()),'Reduced motion should be still');await advance(p,2);await p.screenshot({path:`output/playwright/v21-ending-${fallback?'fallback':'mobile'}.png`,fullPage:true});
 for(const [width,height] of [[320,568],[812,375]]){await p.setViewportSize({width,height});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('#replay').click();await p.keyboard.press('Escape');}
 assert.deepEqual(errs,[]);await p.close();
 }
 console.log('PASS mobile, reduced motion, CSS fallback, graphemes, 320px and landscape');
 const p=await browser.newPage();await ready(p);await p.evaluate(()=>window.__midAutumn.seek('outro',15));const resources=await p.evaluate(()=>window.__midAutumn.resources());for(let i=0;i<5;i++)await p.evaluate(()=>window.__midAutumn.seek('outro',15));assert.deepEqual(await p.evaluate(()=>window.__midAutumn.resources()),resources);await p.evaluate(()=>window.__midAutumn.loseContext());await p.waitForFunction(()=>!window.__midAutumn.measure().webgl);assert.ok((await p.evaluate(()=>window.__midAutumn.measure())).error<=8);await p.close();
 const bad=await browser.newPage({reducedMotion:'reduce'});await bad.route('**/hang-*.webp*',r=>r.abort());await bad.goto(url);await bad.waitForFunction(()=>window.__midAutumn?.state().assetIssue);await bad.locator('#begin').click();await bad.locator('#light-all').click();await bad.locator('#continue-light').click();await advance(bad,6);await wish(bad,'Mong một đêm bình yên');await advance(bad,2);assert.equal(await bad.evaluate(()=>window.__midAutumn.measure().handAvailable),false);assert.equal(await bad.locator('#fallback-letter').isHidden(),true);await advance(bad,2);assert.equal(await bad.locator('body').getAttribute('data-mode'),'ending');await bad.close();
 console.log('PASS stable GPU resources, context loss, missing artwork recovery');
 const main=await browser.newPage();const seasonal=[];main.on('request',r=>{if(r.url().includes('/static/mid-autumn/'))seasonal.push(r.url());});await main.goto(base);assert.equal(await main.locator('#mid-autumn-link').getAttribute('href'),'/trung-thu/');assert.deepEqual(seasonal,[]);await main.close();console.log('PASS main entry link without loading seasonal assets');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
